# Generated by Django 3.0 on 2022-08-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
