# Generated by Django 3.0 on 2022-08-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_lugar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='producto',
            new_name='product',
        ),
    ]
