# Generated by Django 3.0 on 2022-08-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20220805_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='code',
            field=models.ImageField(blank=True, upload_to='code'),
        ),
    ]
