# Generated by Django 3.0 on 2022-08-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='code',
            field=models.ImageField(null=True, upload_to='code'),
        ),
    ]
