# Generated by Django 3.0 on 2022-08-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20220805_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='code',
            field=models.ImageField(blank=True, upload_to='code'),
        ),
    ]
